import { ReadonlyDeep } from "type-fest";

import { RestEndpoint } from "./wrappers/rest-endpoint";

export enum TodoItemType {
	ShortTerm = 0,
	LongTerm = 1,
	StickyNote = 2
}

export function todoItemTypeToString(type: TodoItemType): string {
	switch (type) {
		case TodoItemType.ShortTerm:
			return "Short Term";
		case TodoItemType.LongTerm:
			return "Long Term";
		case TodoItemType.StickyNote:
			return "Sticky Note";
		default:
			throw new Error("Invalid TodoItemType");
	}
}

export function todoItemTypeFromString(type: string): TodoItemType {
	switch (type) {
		case "Short Term":
			return TodoItemType.ShortTerm;
		case "Long Term":
			return TodoItemType.LongTerm;
		case "Sticky Note":
			return TodoItemType.StickyNote;
		default:
			throw new Error("Invalid TodoItemType");
	}
}

export enum TodoItemStatus {
	Active = 0,
	Completed = 1,
	Inactive = 2
}

export function TodoItemStatusToString(status: TodoItemStatus): string {
	switch (status) {
		case TodoItemStatus.Active:
			return "Active";
		case TodoItemStatus.Completed:
			return "Completed";
		case TodoItemStatus.Inactive:
			return "Inactive";
		default:
			throw new Error("Invalid TodoItemStatus");
	}
}

export function TodoItemStatusFromString(status: string): TodoItemStatus {
	switch (status) {
		case "Active":
			return TodoItemStatus.Active;
		case "Completed":
			return TodoItemStatus.Completed;
		case "Inactive":
			return TodoItemStatus.Inactive;
		default:
			throw new Error("Invalid TodoItemStatus");
	}
}

export interface TodoItemRecord {
	/**
	 * Auto generated incremental id
	 */
	id: number;
	/**
	 * URL safe UUID key generated by nanoid
	 */
	uuid: string;
	title: string;
	itemType: TodoItemType;
	status: TodoItemStatus;
	/**
	 * When should this item be completed by?
	 * This will be used by notifications and reminders.
	 */
	due: Date | null;
	/**
	 * Last time this item was updated.
	 */
	updated: Date | null;
	/**
	 * Completed time of this item.
	 */
	completed: Date | null;
	/**
	 * Set to NOW() by default.
	 */
	created: Date;
}

export type TodoItemRecordInsertRequiredFields = Pick<TodoItemRecord, 'title'>;
export type TodoItemRecordInsertOptionalFields = Pick<TodoItemRecord, 'itemType' | 'due' | 'updated' | 'completed' | 'status'>;
export type TodoItemRecordInsertFields = TodoItemRecordInsertRequiredFields & Partial<TodoItemRecordInsertOptionalFields>;

export const DEFAULT_TODO_ITEM_RECORD_FIELDS: TodoItemRecordInsertOptionalFields = {
	itemType: TodoItemType.ShortTerm,
	status: TodoItemStatus.Active,
	due: null,
	updated: null,
	completed: null
};

export interface TodoItemQueryFunctions {
	// Standard queries
	getById: (id: number) => Promise<TodoItemRecord | null>;
	getByUUID: (uuid: string) => Promise<TodoItemRecord | null>;
	insert: (record: TodoItemRecordInsertFields) => Promise<TodoItemRecord>;
	update: (record: TodoItemRecord) => Promise<TodoItemRecord>;
	deleteById: (id: number) => Promise<void>;
	deleteByUUID: (uuid: string) => Promise<void>;
	
	// Specialized queries
	getUpcoming: () => Promise<TodoItemRecord[]>;
	getRecentCreated: () => Promise<TodoItemRecord[]>;
	getRecentCompleted: () => Promise<TodoItemRecord[]>;
	getRecentInactive: () => Promise<TodoItemRecord[]>;	
}


export module TodoRestApi {

	export type TodoItemFilterParams = {
		id: string;
		uuid: string;
		status: string;
		itemType: string;
		completedBefore: string;
		completeAfter: string;
		createdBefore: string;
		createdAfter: string;
		updatedBefore: string;
		updatedAfter: string;
		dueBefore: string;
		dueAfter: string;
		orderBy: string;
	}

	/**
	 * [GET] /todo
	 */
	export type GetTodoItem = RestEndpoint<TodoItemFilterParams, undefined, TodoItemRecord[]>;

	/**
	 * [POST] /todo
	 */
	export type CreateTodoItem = RestEndpoint<{}, {
		title: string;
		itemType: string;
		dueDate: string;
		status: string;
	}, TodoItemRecord>;

	/**
	 * [PUT] /todo/:id
	 */
	export type UpdateTodoItem = RestEndpoint<TodoItemFilterParams, {
		title?: string;
		itemType?: string;
		dueDate?: string;
		status?: string;
	}, TodoItemRecord>;
	
	/**
	 * [DELETE] /todo/:id
	 */
	export type DeleteTodoItem = RestEndpoint<TodoItemFilterParams, undefined, TodoItemRecord>;

}